//Cart
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_ITEM_ERROR = "CART_ITEM_ERROR";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_RESET = "CART_RESET";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";

//Order Admin List
export const ORDER_ADMIN_LIST_FAIL = "ORDER_ADMIN_LIST_FAIL";
export const ORDER_ADMIN_LIST_REQUEST = "ORDER_ADMIN_LIST_REQUEST";
export const ORDER_ADMIN_LIST_SUCCESS = "ORDER_ADMIN_LIST_SUCCESS";

//Order Create
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";

//Order Deliver
export const ORDER_DELIVER_FAIL = "ORDER_DELIVER_FAIL";
export const ORDER_DELIVER_REQUEST = "ORDER_DELIVER_REQUEST";
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET";
export const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS";

///Order Detail
export const ORDER_DETAIL_FAIL = "ORDER_DETAIL_FAIL";
export const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST";
export const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS";

//Order List
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";
export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_RESET = "ORDER_LIST_RESET";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";

//Order Pay
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";

//Product Create
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";

//Product Create Review
export const PRODUCT_REVIEW_FAIL = "PRODUCT_REVIEW_FAIL";
export const PRODUCT_REVIEW_REQUEST = "PRODUCT_REVIEW_REQUEST";
export const PRODUCT_REVIEW_RESET = "PRODUCT_REVIEW_RESET";
export const PRODUCT_REVIEW_SUCCESS = "PRODUCT_REVIEW_SUCCESS";

//Product Delete
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";
export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_RESET = "PRODUCT_DELETE_RESET";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";

//Product Detail
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";
export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";

//Product Edit
export const PRODUCT_EDIT_FAIL = "PRODUCT_EDIT_FAIL";
export const PRODUCT_EDIT_REQUEST = "PRODUCT_EDIT_REQUEST";
export const PRODUCT_EDIT_RESET = "PRODUCT_EDIT_RESET";
export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS";

//Product List
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";

//Product Top
export const PRODUCT_TOP_FAIL = "PRODUCT_TOP_FAIL";
export const PRODUCT_TOP_REQUEST = "PRODUCT_TOP_REQUEST";
export const PRODUCT_TOP_SUCCESS = "PRODUCT_TOP_SUCCESS";

//User Delete
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_RESET = "USER_DELETE_RESET";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";

//User Detail
export const USER_DETAIL_FAIL = "USER_DETAIL_FAIL";
export const USER_DETAIL_REQUEST = "USER_DETAIL_REQUEST";
export const USER_DETAIL_RESET = "USER_DETAIL_RESET";
export const USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS";

//User Edit
export const USER_EDIT_FAIL = "USER_EDIT_FAIL";
export const USER_EDIT_REQUEST = "USER_EDIT_REQUEST";
export const USER_EDIT_RESET = "USER_EDIT_RESET";
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";
//User List
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_RESET = "USER_LIST_RESET";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";

//User Login
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";

//User Register
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";

//User Update Profile
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
